routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Frontend\FrontController@index')->name('/');
Route::get('post', 'Frontend\FrontController@post')->name('post');

// Route Group
Route::group(['prefix' => 'admin'], function() {
    Route::get('dashboard', 'Frontend\FrontController@index');
    Route::get('create', 'Frontend\FrontController@index');
    Route::get('list', 'Frontend\FrontController@index');
    Route::get('users', 'Frontend\FrontController@index');
});

// ==================================================================================
Route::get('register', 'Frontend\FrontController@register')->name('register');
Route::post('register', 'Frontend\FrontController@registerUser');

Route::get('verify/{token}', 'Frontend\FrontController@verifyEmail')->name('verify');

Route::get('login', 'Frontend\FrontController@login')->name('login');
Route::post('login', 'Frontend\FrontController@loginUser');

Route::get('logout', 'Frontend\FrontController@logout')->name('logout');

Route::group(['middleware' => 'auth'], function() {

    Route::get('dashboard', 'Frontend\FrontController@dashboard')->name('dashboard');

    // categories
    Route::get('categories', 'Backend\CategoryController@index')->name('categories.index');
    Route::get('categories/add', 'Backend\CategoryController@create')->name('categories.create');
    Route::post('categories', 'Backend\CategoryController@store')->name('categories.store');
    Route::get('categories/{id}', 'Backend\CategoryController@show')->name('categories.show');
    Route::get('categories/{id}/edit', 'Backend\CategoryController@edit')->name('categories.edit');
    Route::put('categories/{id}', 'Backend\CategoryController@update')->name('categories.update');
    Route::delete('categories/{id}', 'Backend\CategoryController@delete')->name('categories.delete');

    // posts
    Route::resource('posts', 'Backend\PostController');

});

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Events\PostCreated;
use App\Events\PostUpdated;
use App\Events\PostDeleted;

class Post extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'user_id', 
        'category_id', 
        'title', 
        'content', 
        'thumbnail_path', 
        'status' 
    ];

    protected $dates = [
        'created_at'
    ];

    protected $dispatchesEvents = [
        'created'   => PostCreated::class,
        'updated'   => PostUpdated::class,
        'deleted'   => PostDeleted::class
    ];

    /**
     * Defining relationship between Post & Category Model.
     * Actually one post must have under a category
     * So, that's why we use the method named belongsTo()
     * And the method name should be single 
     * Because, from post to category referes to one to one relationship
     */
    public function category()
    {
        return $this->belongsTo(Category::class, 'category_id');
    }

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

}

app/Http/Controllers/Backend/CategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;
use App\Models\Category;

class CategoryController extends Controller
{
    public function index()
    {
        $data = [];
        $data['site_title'] = 'Laravel Advanced';
        $data['links'] = [
            'Facebook'  => 'https://facebook.com',
            'Twitter'   => 'https://twitter.com',
            'Google'    => 'https://google.com',
            'YouTube'   => 'https://youtube.com',
            'LinkedIn'  => 'https://linkedin.com'
        ];

        $data['categories'] = Category::select('id', 'name', 'slug', 'status')->paginate(10);
        // N.B: paginate() or simplePaginate()

        return view('backend.category.index', $data);
    }

    public function create()
    {
        $data = [];
        $data['site_title'] = 'Laravel Advanced';
        $data['links'] = [
            'Facebook'  => 'https://facebook.com',
            'Twitter'   => 'https://twitter.com',
            'Google'    => 'https://google.com',
            'YouTube'   => 'https://youtube.com',
            'LinkedIn'  => 'https://linkedin.com'
        ];

        return view('backend.category.create', $data);
    }

    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name'      => 'required|unique:categories,name',
            'status'    => 'required'
        ]);

        if($validator->fails())
        {
            return redirect()->back()->withErrors($validator)->withInput();
        }

        Category::create([
            'name'  => trim($request->input('name')),
            'slug'  => str_slug(trim($request->input('name'))),
            'status'=> $request->input('status')
        ]);

        session()->flash('type', 'success');
        session()->flash('message', 'Category Added');

        return redirect()->back();
    }

    public function show($id)
    {
        $data = [];
        $data['site_title'] = 'Laravel Advanced';
        $data['links'] = [
            'Facebook'  => 'https://facebook.com',
            'Twitter'   => 'https://twitter.com',
            'Google'    => 'https://google.com',
            'YouTube'   => 'https://youtube.com',
            'LinkedIn'  => 'https://linkedin.com'
        ];
        $data['category'] = Category::with('posts', 'posts.user')->select('id', 'name', 'slug', 'status', 'created_at')->find($id);

        return view('backend.category.show', $data);
    }

    public function edit($id)
    {
        $data = [];
        $data['site_title'] = 'Laravel Advanced';
        $data['links'] = [
            'Facebook'  => 'https://facebook.com',
            'Twitter'   => 'https://twitter.com',
            'Google'    => 'https://google.com',
            'YouTube'   => 'https://youtube.com',
            'LinkedIn'  => 'https://linkedin.com'
        ];
        $data['category'] = Category::select('id', 'name', 'slug', 'status', 'created_at')->find($id);

        return view('backend.category.edit', $data);
    }

    public function update($id, Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name'      => 'required|unique:categories,name,' . $id,
            'status'    => 'required'
        ]);

        if($validator->fails())
        {
            return redirect()->back()->withErrors($validator)->withInput();
        }

        $category = Category::find($id);

        $category->update([
            'name'  => trim($request->input('name')),
            'slug'  => str_slug(trim($request->input('name'))),
            'status'=> $request->input('status')
        ]);

        session()->flash('type', 'success');
        session()->flash('message', 'Category Updated');

        return redirect()->back();
    }

    public function delete($id)
    {
        $category = Category::find($id);

        $category->delete();

        session()->flash('type', 'success');
        session()->flash('message', 'Category Deleted');

        return redirect()->route('categories.index');
    }

}

app/Http/Controllers/Backend/PostController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;
use App\Models\Post;
use App\Models\Category;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = [];
        $data['site_title'] = 'Laravel Advanced';
        $data['links'] = [
            'Facebook'  => 'https://facebook.com',
            'Twitter'   => 'https://twitter.com',
            'Google'    => 'https://google.com',
            'YouTube'   => 'https://youtube.com',
            'LinkedIn'  => 'https://linkedin.com'
        ];

        $data['posts'] = Post::with('category', 'user')->select('id', 'title', 'user_id', 'category_id', 'status')->paginate(10);
        // N.B: paginate() or simplePaginate()

        return view('backend.post.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = [];
        $data['site_title'] = 'Laravel Advanced';
        $data['links'] = [
            'Facebook'  => 'https://facebook.com',
            'Twitter'   => 'https://twitter.com',
            'Google'    => 'https://google.com',
            'YouTube'   => 'https://youtube.com',
            'LinkedIn'  => 'https://linkedin.com'
        ];
        $data['categories'] = Category::select('name', 'id')->get();

        return view('backend.post.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'title'         => 'required',
            'content'       => 'required',
            'category_id'   => 'required',
            'status'        => 'required'
        ]);

        if($validator->fails())
        {
            return redirect()->back()->withErrors($validator)->withInput();
        }

        Post::create([
            'title'         => trim($request->input('title')),
            'content'       => trim($request->input('content')),
            'category_id'   => $request->input('category_id'),
            'status'        => $request->input('status'),
            'thumbnail_path'=> 'default.png',
            'user_id'       => auth()->user()->id,
        ]);

        session()->flash('type', 'success');
        session()->flash('message', 'Post Added');

        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/backend/post/create.blade.php
@extends('app')

@section('content')

    @if ($errors->any())
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>
                        {{ $error }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </li>
                @endforeach
            </ul>
        </div>
    @endif

    @if(session('message'))
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <ul>
                <li>
                    {{ session('message') }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </li>
            </ul>
        </div>
    @endif

    <h2>Add Post</h2>

    <hr>

    <form action="{{ route('posts.store') }}" method="POST" enctype="multipart/form-data">
        @csrf
        <div class="form-group">
            <label for="title">Post Title</label>
            <input type="text" name="title" {{ old('title') }} class="form-control" id="title"  placeholder="Enter post title">
        </div>

        <div class="form-group">
            <label for="content">Post Content</label>
            <textarea class="form-control" name="content"></textarea>
        </div>

        <div class="form-group">
            <label for="category_id">Category</label>
            <select name="category_id" class="form-control">

                @foreach($categories as $category)
                    <option value="{{ $category->id }}">{{ $category->name }}</option>
                @endforeach

            </select>
        </div>

        <div class="form-group">
            <label for="status">Status</label>
            <select name="status" class="form-control">
                <option value="1">Active</option>
                <option value="0">Inactive</option>
            </select>
        </div>

        <button type="submit" class="btn btn-primary btn-block">Add Post</button>
    </form>

    <hr/>

    <p>
        <a href="{{ route('posts.index') }}" class="btn btn-primary btn-block">
            Back to Post List
        </a>
    </p>

@endsection

resources/views/backend/post/edit.blade.php
@extends('app')

@section('content')

    @if ($errors->any())
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>
                        {{ $error }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </li>
                @endforeach
            </ul>
        </div>
    @endif

    @if(session('message'))
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <ul>
                <li>
                    {{ session('message') }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </li>
            </ul>
        </div>
    @endif

    <h2>Edit Category</h2>

    <hr>

    <form action="{{ route('categories.update', $category->id) }}" method="POST" enctype="multipart/form-data">
        
        @csrf
        @method('PUT')

        <div class="form-group">
            <label for="name">Category Name</label>
            <input type="text" name="name" value="{{ $category->name }}" {{ old('name') }} class="form-control" id="name"  placeholder="Enter category name">
        </div>

        <div class="form-group">
            <label for="status">Status</label>
            <select name="status" class="form-control">
                <option value="1" @if($category->status === 1) selected @endif>Active</option>
                <option value="0" @if($category->status === 0) selected @endif>Inactive</option>
            </select>
        </div>

        <button type="submit" class="btn btn-primary btn-block">Edit Category</button>
    </form>

    <hr/>

    <p>
        <a href="{{ route('categories.index') }}" class="btn btn-primary btn-block">
            Back to Category List
        </a>
    </p>

@endsection

resources/views/backend/post/index.blade.php
@extends('app')

@section('content')

    <div class="well">

        <h2>Post List</h2>

        <p>
            <a href="{{ route('posts.create') }}" class="btn btn-success">Add Post</a>
        </p>

        @if(session('message'))
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                {{ session('message') }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        @endif

        <table class="table table-bordered table-condensed">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Post Title</th>
                    <th>Category</th>
                    <th>Author</th>
                    <th>Status</th>
                    <th>Action</th>
                </tr>
            </thead>
            
            @foreach($posts as $post)
            
            <tr>
                <td>{{ $post->id }}</td>
                <td>{{ $post->title }}</td>
                <td>{{ $post->category->name }}</td>
                <td>{{ $post->user->username }}</td>
                <td>{{ $post->status === 1 ? 'Active' : 'Inactive' }}</td>
                <td>
                    <a href="{{ route('posts.show', $post->id) }}" class="btn btn-info">
                        Details
                    </a>
                </td>
            </tr>

            @endforeach

        </table>

        {!! $posts->links() !!}
    </div>

@endsection

resources/views/backend/post/show.blade.php
@extends('app')

@section('content')
    <h2>{{ $category->name }}</h2>

    <p>
        ID: {{ $category->id }}
    </p>

    <p>
        Slug: {{ $category->slug }}
    </p>

    <p>
        Status: {{ $category->status === 1 ? 'Active' : 'Inactive' }}
    </p>

    <p>
        Created at: {{ $category->created_at }}
    </p>

    <div>
        <a href="{{ route('categories.edit', $category->id) }}" class="btn btn-info btn-block">
            Edit
        </a>
    </div>

    <hr>

    <div>
        <form action="{{ route('categories.delete', $category->id) }}" method="POST" onsubmit="return confirm('Are you sure to delete?');">
            @csrf
            @method('DELETE')
            <button type="submit" class="btn btn-danger btn-block">Delete</button>
        </form>
    </div>

    <hr>

    <p>
        <a href="{{ route('categories.index') }}" class="btn btn-primary btn-block">
            Back to Category List
        </a>
    </p>
    
@endsection